
using LOS.Adapter.Data.Services.Query.Base;

namespace LOS.Adapter.Data.Services.Query
{
    /// <summary>
    /// 
    /// </summary>
    public class GetObligationRequest : BaseRequest<GetObligationResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetObligationRequest"/> class.
        /// </summary>
        /// <param name="user">The user.</param>
        /// <param name="pass">The pass.</param>
        /// <param name="bankId">The bank identifier.</param>
        /// <param name="obligorNumber">The obligor number.</param>
        /// <param name="batchid">The batchid.</param>
        /// <param name="obligationNumber">The obligation number.</param>
        /// <param name="segment">The segment.</param>
        /// <param name="restriction">The restriction.</param>
        /// <param name="dataLength">Length of the data.</param>
        /// <param name="itemNumber">The item number.</param>
        /// <param name="luw">The luw.</param>
        /// <param name="restartRequestCode">The restart request code.</param>
        public GetObligationRequest(string user, string pass, string bankId, string obligorNumber, string batchid, string obligationNumber, string segment, string restriction, string dataLength, string itemNumber, string luw, string restartRequestCode)
            : base(user, pass, luw, bankId, obligorNumber, batchid, obligationNumber, segment, restriction, dataLength, itemNumber, restartRequestCode)
        {

        }

    }

    /// <summary>
    /// 
    /// </summary>
    public class GetObligationResponse : BaseResponse
    {
        public string x103A_PROC_TYPE { get; set; }
        public string x103A_EFF_DATE { get; set; }
        public string x103A_MATUR_DATE { get; set; }
        public string x103A_EST_MATUR_DATE { get; set; }
        public decimal x103A_ORIG_AMT { get; set; }
        public decimal x103A_CURR_AMT { get; set; }
        public decimal x103A_AVAILABILITY { get; set; }
        public string x103A_TKDOWN_OBLR { get; set; }
        public string x103A_TKDOWN_OBLN { get; set; }
        public decimal x103A_COMMITMENT_BAL { get; set; }
        public string x103B_PREPAY_CODE { get; set; }
        public string x103B_PREPAY_CODE_LIT { get; set; }
        public string x103B_DUR_CODE { get; set; }
        public string x103B_DUR_CODE_LIT { get; set; }
        public string x103B_SECUR_CODE { get; set; }
        public string x103B_SECUR_CODE_LIT { get; set; }
        public string x103B_MARGIN_CODE { get; set; }
        public string x103B_MARGIN_CODE_LIT { get; set; }
        public string x103B_REG_UZ { get; set; }
        public string x103B_REG_UZ_LIT { get; set; }
        public string x103B_TAX_BANK { get; set; }
        public string x103B_TAX_BANK_LIT { get; set; }
        public string x103B_NOTE_RESET_IND { get; set; }
        public string x103B_NOTE_RESET_IND_LIT { get; set; }
        public string x103B_BILL_LIMIT_CODE { get; set; }
        public string x103B_BILL_LIMIT_CODE_LIT { get; set; }
        public string x103B_TRANS_NOTICE { get; set; }
        public string x103B_TRANS_NOTICE_LIT { get; set; }
        public string x103B_1098_INDICATOR { get; set; }
        public string x103B_1098_INDICATOR_LIT { get; set; }
        public string x103C_ORIG_OBLN_DATE { get; set; }
        public decimal x103C_ORIG_OBLN_AMT { get; set; }
        public string x103C_DATE_LAST_RENEWED { get; set; }
        public string x103C_CLOSE_OPT_IND { get; set; }
        public string x103C_CLOSE_OPT_IND_LIT { get; set; }
        public string x103C_CLOSE_IND { get; set; }
        public string x103C_CLOSE_IND_LIT { get; set; }
        public decimal x103C_CLOSE_TOL_AMT { get; set; }
        public string x103C_PD_OFF_NOTICE { get; set; }
        public string x103C_PD_OFF_NOTICE_LIT { get; set; }
        public string x103D_CONT_OFF { get; set; }
        public string x103D_SERV_UNIT { get; set; }
        public string x103D_ASSIGN_UNIT { get; set; }
        public string x103D_FED_CLASS { get; set; }
        public string x103D_OBLN_TYPE { get; set; }
        public string x103D_PURPOSE_CODE { get; set; }
        public string x103D_GEN_LEDG { get; set; }
        public string x103D_COLLAT_TYPE { get; set; }
        public string x103D_LCHG_PRM_REASON { get; set; }
        public string x103D_LCHG_FORMULA_TYPE { get; set; }
        public string x103D_SCHED_BAL_IND { get; set; }
        public string x103E_STAT_CODE { get; set; }
        public string x103E_STAT_CODE_LIT { get; set; }
        public string x103E_FROZEN_STAT_FLAG { get; set; }
        public string x103E_FROZEN_STAT_FLAG_LIT { get; set; }
        public string x103F_EXAM_TYPE_1 { get; set; }
        public string x103F_EXAM_TYPE_1_LIT { get; set; }
        public string x103F_EXAM_CLASS_1 { get; set; }
        public string x103F_FACILITY_RISK_RATING { get; set; }
        public string x103F_EXAM_DATE_1 { get; set; }
        public string x103F_ORIG_TERM_MONTHS { get; set; }
        public string x103F_CREDIT_SCORE { get; set; }
        public string x103F_CREDIT_DATE { get; set; }
        public string x103F_BKVAL_DATE { get; set; }
        public string x103G_COLLECTION_MONITOR { get; set; }
        public string x103G_COLLECTION_MONITOR_LIT { get; set; }
        public string x103G_ALT_NAME_ADR_CD { get; set; }
        public string x103H_CRA_IND { get; set; }
        public string x103H_RT_SITEID { get; set; }
        public string x103H_PROD_DEF_CODE { get; set; }
        public string x103H_BILL_TYPE_CODE { get; set; }
        public string x103H_USER_CODE_1 { get; set; }
        public string x103H_USER_DATE_1 { get; set; }
        public string x103H_USER_ALPHA { get; set; }
        public string x103K_SPECIAL_CO__INDICATOR { get; set; }
        public string x103K_CREDIT_DESK_REF_NBR { get; set; }
        public string x103K_CASH_FLOW_RATIO { get; set; }
        public string x103K_LOAN_VALUE_RATIO { get; set; }
        public string x103K_REFERRING_OFFICER { get; set; }
        public string x103K_SECONDARY_OFFICER { get; set; }
        public string x103K_AFS_ALPHA_1 { get; set; }
        public string x103L_CREDIT_SC_REF_NO { get; set; }
        public string x103L_ORIG_LTV_DATE { get; set; }
        public string x103L_ORIG_LTV { get; set; }
        public string x103L_REFERRING_OFFICER { get; set; }
        public string x103L_UNDERWRITER { get; set; }
        public string x103N_USER_CODE_2 { get; set; }
        public string x103N_USER_CODE_3 { get; set; }
        public string x1BAA_SBA_STATUS { get; set; }
        public string x1BAA_SBA_STATUS_LIT { get; set; }
        public string x1BAA_SBA_GP_NUMBER { get; set; }
        public string x1BAA_SBA_PROGRAM_NUMBER { get; set; }
        public string x1BAA_APPROVAL_DATE { get; set; }
        public string x1BAA_APPROVAL_AMOUNT { get; set; }
        public string x1BAA_GUARANTEED_PCT { get; set; }
        public string x1BAA_FTA_SERVIC_FEE_PCT { get; set; }
        public string x1BAA_SBA_SOURCE_CODE { get; set; }
        public string x1BAA_SBA_OBGR_NO { get; set; }
        public string x1BAA_SPEC_MAIL_CODE { get; set; }
        public string x1BAA_DATE_SOLD { get; set; }
        public string x1BAA_SETTLEMENT_DATE { get; set; }
        public string x1BAA_SERVICE_FEE_AMT { get; set; }
        public string x1BAA_SERVICE_FEE_PCT { get; set; }
        public string x1BAA_SPREAD_PMT_OPT { get; set; }
        public string x1BAA_SPREAD_PMT_OPT_LIT { get; set; }
        public string x103A_TITLE_CURR_DATE { get; set; }
        public string x103A_POSTED_DATE { get; set; }
        public string x103A_LAST_ACT_DATE { get; set; }
        public string x103A_LAST_CHG_DATE { get; set; }
        public decimal x103A_GUAR_AMT { get; set; }
        public decimal x103A_COLLAT_VALUE { get; set; }
        public decimal x103A_PAID_TO_PRIN { get; set; }
        public decimal x103A_USER_BALANCE { get; set; }
        public decimal x103A_BOOK_VALUE { get; set; }
        public decimal x103A_SCHED_BALANCE { get; set; }
        public decimal x103A_PART_AMT { get; set; }
        public decimal x103A_AMT_TKNDWN { get; set; }
        public decimal x103A_NET_BOOK_VALUE { get; set; }
        public decimal x103A_PROCEEDS { get; set; }
        public decimal x103A_NET_PRIN_TDY { get; set; }
        public decimal x103A_NET_PARTS_TDY { get; set; }
        public decimal x103A_NET_COLLAT_ACTIVITY { get; set; }
        public decimal x103A_NET_INT_TDY { get; set; }
        public string x103A_INTER_COMM { get; set; }
        public string x103A_R { get; set; }
        public string x103A_RS { get; set; }
        public string x103A_RL { get; set; }
        public string x103A_LINE_23_LIT { get; set; }
        public string x103B_PRIN_PD_TO_DT { get; set; }
        public string x103B_PRIN_LAST_BILL_DT { get; set; }
        public string x103B_PRIN_PREV_DUE_DT { get; set; }
        public decimal x103B_PRIN_PAID_MTD { get; set; }
        public decimal x103B_PRIN_PAID_YTD { get; set; }
        public decimal x103B_PRIN_PAID_NOT_BLD { get; set; }
        public decimal x103B_PRIN_WAIVE_AMT { get; set; }
        public decimal x103B_BILL_AGING_AMOUNT { get; set; }
        public decimal x103B_MTHLY_CUM_BAL { get; set; }
        public string x103B_DATE_NEXT_DUE { get; set; }
        public decimal x103B_PREV_YR_AVG_USE { get; set; }
        public string x103B_PRIN_BLD_NT_PD_LT { get; set; }
        public decimal x103B_PRIN_BLD_NOT_PAID { get; set; }
        public decimal x103B_PRIN_PAST_DUE { get; set; }
        public decimal x103B_CAPITALIZED_INT { get; set; }
        public string x103B_DISC_CODE { get; set; }
        public string x103B_MARGIN_PCT { get; set; }
        public string x103B_REDISC_CODE { get; set; }
        public string x103B_ACCR_LIMIT_CODE { get; set; }
        public string x103B_FLOAT_IND { get; set; }
        public string x103B_RT_CHG_NOTICE { get; set; }
        public string x103B_CUST_EXP_IND { get; set; }
        public string x103B_EXCLUDE_CD { get; set; }
        public string x103B_LC_REF_NUMBER { get; set; }
        public string x103B_PREPAY_PENALTY_IND { get; set; }
        public string x103C_RENEW_TIMES { get; set; }
        public string x103C_RENEW_TYPE { get; set; }
        public string x103C_ORIG_MATUR_DATE { get; set; }
        public decimal x103C_ORIG_DISC_AMT { get; set; }
        public string x103C_RENEW_PREV { get; set; }
        public string x103C_RENEW_TO { get; set; }
        public string x103C_RENEWAL_POSTED_DT { get; set; }
        public string x103C_REFINANCED_FROM_OBLN { get; set; }
        public string x103C_REFINANCED_TO_OBLN { get; set; }
        public string x103C_ASSUMED_FROM_OBGR { get; set; }
        public string x103C_ASSUMED_TO_OBGR { get; set; }
        public string x103C_ASSUMED_FROM_OBLN { get; set; }
        public string x103C_ASSUMED_TO_OBLN { get; set; }
        public string x103C_DATE_LAST_EXTEND { get; set; }
        public string x103C_TIMES_EXTEND { get; set; }
        public string x103C_MNTHS_EXTEND { get; set; }
        public string x103C_CLOSE_DT { get; set; }
        public decimal x103C_CLOSE_AMT { get; set; }
        public string x103C_YESTERDAYS_CLOSE { get; set; }
        public string x103C_HI_ADV_IND { get; set; }
        public string x103C_IMA_TKDWN_IND { get; set; }
        public string x103C_FINAL_CLOSE_IND { get; set; }
        public decimal x103C_FINAL_CLOSE_PRIN_ADJ { get; set; }
        public string x103C_FINAL_CLOSE_POST_DATE { get; set; }
        public decimal x103C_FINAL_CLOSE_PRIN_WVE { get; set; }
        public string x103C_WAIVE_EARN_IND { get; set; }
        public string x103C_NON_RESTART_DATE { get; set; }
        public string x103C_OUT_DEBT_DATE { get; set; }
        public string x103D_LAST_WEKLY_DATE { get; set; }
        public string x103D_LAST_DAILY_DATE { get; set; }
        public string x103D_DIVISION { get; set; }
        public string x103D_REGION { get; set; }
        public string x103D_SUB_LOB { get; set; }
        public string x103D_SIC_CODE { get; set; }
        public string x103D_GEOG_CODE { get; set; }
        public string x103D_PNLTY_FORMULA { get; set; }
        public string x103D_GROUP { get; set; }
        public string x103D_MARKET { get; set; }
        public string x103D_CNTL_BRK_U_HIERARCHY { get; set; }
        public string x103D_REAM_INDICATOR { get; set; }
        public string x103D_REAM_BASIS_IND { get; set; }
        public string x103D_REAM_FREQ_MONTHS { get; set; }
        public string x103D_REAM_PRIORITY { get; set; }
        public string x103D_REAM_NXT_SCHD_DT { get; set; }
        public string x103D_LAST_REAM_DATE { get; set; }
        public string x103D_REAM_PERIOD_DATE { get; set; }
        public string x103D_CUST_NOTIFY_DAYS { get; set; }
        public string x103D_REAM_ERR_EFF_DT { get; set; }
        public string x103D_LAST_NOTICE_DATE { get; set; }
        public decimal x103D_CURR_BALLOON { get; set; }
        public string x103D_LAST_CHANGE_DATE { get; set; }
        public decimal x103D_ORIG_BALLOON { get; set; }
        public string x103D_REDISCLOSE_DATE { get; set; }
        public string x103D_TERM_OUT_STATUS { get; set; }
        public string x103D_SCHED_BAL_ROUND { get; set; }
        public string x103D_LEGAL_STATUS { get; set; }
        public string x103D_LEGAL_STATUS_DATE { get; set; }
        public string x103D_ADVANCE_OPT { get; set; }
        public string x103D_CURTAILMENT_OPT { get; set; }
        public string x103D_UNAPPLIED_OPT { get; set; }
        public string x103D_PMT_SPRD_SEQ { get; set; }
        public string x103D_MATURITY_PMT_SPRD { get; set; }
        public string x103E_STAT_DATE { get; set; }
        public string x103E_CHG_OFF_DATE { get; set; }
        public string x103E_NON_PERFM_DT { get; set; }
        public string x103E_CHARGE_OFF_STATUS { get; set; }
        public string x103E_CHG_OFF_RECOV { get; set; }
        public decimal x103E_RECOVERY_AMT_ITD { get; set; }
        public string x103E_E_SUSP_AMORT_DT { get; set; }
        public string x103E_NON_PERFM_OVRD { get; set; }
        public string x103E_ACCRL_MNTR_FLAG { get; set; }
        public string x103E_NON_PERFM_IND { get; set; }
        public string x103E_NON_ACCRL_DATE { get; set; }
        public string x103E_NON_ACCRL_OVRD { get; set; }
        public string x103E_REDUCED_RT_IND { get; set; }
        public string x103E_RENEG_FLAG { get; set; }
        public string x103E_FROZEN_STAT_DATE { get; set; }
        public string x103E_FROZ_OPT { get; set; }
        public string x103E_FROZ_CHG_DAYS { get; set; }
        public string x103E_FROZ_LEAD_DAYS { get; set; }
        public string x103E_FROZ_AUTO_RESUM_DAYS { get; set; }
        public string x103E_FROZ_AUTO_RESUME_DATE { get; set; }
        public decimal x103E_CHARGE_OFF_ITD { get; set; }
        public string x103E_IMPAIRMENT_IND { get; set; }
        public string x103E_IMPAIRMENT_DATE { get; set; }
        public string x103E_DATE_LAST_IMPAIRED { get; set; }
        public decimal x103E_VALUATION_AMT { get; set; }
        public decimal x103E_VALUATION_ALLOWANCE { get; set; }
        public string x103E_VALUATION_DATE { get; set; }
        public string x103E_VALUATION_IND { get; set; }
        public string x103E_MARK_TO_MARKET_PCT { get; set; }
        public decimal x103E_ORIG_SUSPENSE_AMT { get; set; }
        public decimal x103E_LOST_INCOME_MTD { get; set; }
        public decimal x103E_PAID_NON_ACCRL_YTD { get; set; }
        public decimal x103E_LOST_INCOME_QTD { get; set; }
        public decimal x103E_LOST_INCOME_YTD { get; set; }
        public decimal x103F_BKVAL_PRIN_BAL { get; set; }
        public decimal x103F_BKVAL_ORIG_BAL { get; set; }
        public decimal x103F_BKVAL_AMT_TKDOWN { get; set; }
        public decimal x103F_EXAM_AMT_1 { get; set; }
        public decimal x103F_BKVAL_INT_OVER { get; set; }
        public string x103F_EXAM_TYPE_2 { get; set; }
        public decimal x103F_BKVAL_CHG_OFF_BAL { get; set; }
        public string x103F_EXAM_CLASS_2 { get; set; }
        public decimal x103F_BKVAL_USER_BAL { get; set; }
        public string x103F_EXAM_DATE_2 { get; set; }
        public decimal x103F_EXAM_AMT_2 { get; set; }
        public string x103F_COUP_POST_DATE_REPL { get; set; }
        public string x103F_COUP_REPL_1ST_DUE_DATE { get; set; }
        public string x103F_COUP_REORDER_NUMB { get; set; }
        public string x103F_COUP_ORDER_FREQ { get; set; }
        public string x103F_COUP_DATE_NEXT_ORDER { get; set; }
        public string x103F_NUMB_ORIG_PYMNTS { get; set; }
        public string x103F_OBLGN_XREF_NO { get; set; }
        public string x103G_PASTDUE_DATE { get; set; }
        public decimal x103G_TOT_PAST_DUE_AMT { get; set; }
        public string x103G_CURR_PAST_DUE_DAYS { get; set; }
        public string x103G_ADV_AFTER_MAT_OPT { get; set; }
        public string x103G_PREV_COLLECT_STATUS { get; set; }
        public string x103G_CURR_COLLECT_STATUS { get; set; }
        public string x103G_TIMES_IN_COLLECTION { get; set; }
        public string x103G_COLLECTION_UNIT { get; set; }
        public string x103G_COLLECTION_OFFICER { get; set; }
        public string x103G_PENALTY_BKVAL_DATE { get; set; }
        public string x103G_PENALTY_CONV_DATE { get; set; }
        public string x103G_RET_CHECK_CTR { get; set; }
        public string x103G_TIMES_PAST_30_DAYS { get; set; }
        public string x103G_TIMES_PAST_60_DAYS { get; set; }
        public string x103G_DELINQ_15_COUNTER { get; set; }
        public string x103G_DELINQ_120_COUNTER { get; set; }
        public string x103G_TIMES_PAST_90_DAYS { get; set; }
        public string x103G_DELINQ_30_COUNTER { get; set; }
        public string x103G_DELINQ_150_COUNTER { get; set; }
        public string x103G_TIMES_PAST_120_DAYS { get; set; }
        public string x103G_DELINQ_60_COUNTER { get; set; }
        public string x103G_DELINQ_180_COUNTER { get; set; }
        public string x103G_TIMES_PAST_150_DAYS { get; set; }
        public string x103G_DELINQ_90_COUNTER { get; set; }
        public decimal x103G_MAT_TOLERANCE_PERCENT { get; set; }
        public string x103G_SETTLEMENT_DATE { get; set; }
        public decimal x103G_MAT_TOLERANCE_AMT { get; set; }
        public string x103G_SETTLEMENT_PD { get; set; }
        public string x103G_LOAN_TYPE { get; set; }
        public string x103G_CUSIP_NO { get; set; }
        public string x103G_SNC_CODE { get; set; }
        public string x103G_SNC_ID { get; set; }
        public string x103H_COLL_SHRTGE_CD { get; set; }
        public string x103H_USER_CODE_1_TITLE { get; set; }
        public string x103H_COLL_SHRTGE_DATE { get; set; }
        public string x103H_USER_DATE_2 { get; set; }
        public string x103H_USER_CODE_2_TITLE { get; set; }
        public string x103H_USER_CODE_2 { get; set; }
        public string x103H_COLL_UNDERMARGIN_DATE { get; set; }
        public string x103H_USER_CODE_3 { get; set; }
        public string x103H_COMP_BAL_IND { get; set; }
        public decimal x103H_USER_AMT { get; set; }
        public string x103H_SMSA_CODE { get; set; }
        public string x103H_USER_FIELD_1_TITLE { get; set; }
        public string x103H_USER_FIELD_1 { get; set; }
        public decimal x103H_CENSUS_TRACT { get; set; }
        public string x103H_HOEPA_STATUS { get; set; }
        public string x103H_RATE_SPRD { get; set; }
        public string x103H_PROPERTY_TYPE { get; set; }
        public decimal x103H_INCOME_REVENUE { get; set; }
        public string x103H_PURCHASER_TP { get; set; }
        public string x103H_BUDGET_ID { get; set; }
        public string x103H_MASTER_DOC { get; set; }
        public string x103H_FC824 { get; set; }
        public string x103H_ACH_DELAY_DAYS { get; set; }
        public string x103H_FC826 { get; set; }
        public string x103H_DEFRD_DUE_DATE_IND { get; set; }
        public string x103H_DEFRD_DUE_DATE_DAYS { get; set; }
        public string x103H_UNIT_ACCR_IND { get; set; }
        public string x103H_BALLOON_IND { get; set; }
        public decimal x103H_CONVERSION_PCT { get; set; }
        public string x103H_MATUR_BILL_IND { get; set; }
        public decimal x103H_RISK_WEIGHT_PCT { get; set; }
        public string x103H_TAX_EQUIV_NO { get; set; }
        public string x103H_OBLN_TAX_CLASS { get; set; }
        public decimal x103H_PRIN_OVERDUE { get; set; }
        public decimal x103H_INT_OVERDUE { get; set; }
        public string x103H_BILL_ALONE_IND { get; set; }
        public string x103H_DEAL_NUMBER { get; set; }
        public string x103H_NAICS_CODE { get; set; }
        public string x103K_USER_OFFICER_1 { get; set; }
        public string x103K_USER_OFFICER_2 { get; set; }
        public string x103K_AFS_ALPHA_2 { get; set; }
        public string x103K_USER_OFFICER_3 { get; set; }
        public string x103K_AFS_ALPHA_3 { get; set; }
        public string x103K_USER_OFFICER_4 { get; set; }
        public string x103K_AFS_ALPHA_4 { get; set; }
        public string x103K_AFS_ALPHA_5 { get; set; }
        public string x103K_PREV_TKDWN_FROM_OBLIGOR { get; set; }
        public string x103K_TIED_TO_POSTING_DATE { get; set; }
        public string x103K_PREV_TKDWN_FROM_OBLIGAT { get; set; }
        public string x103K_UNTIED_FROM_POSTING_DATE { get; set; }
        public string x103K_PREV_PROCESS_TYPE { get; set; }
        public string x103K_ORIG_TIE_UNTIE_ACTIV_DAT { get; set; }
        public string x103K_CRED_BUREAU_ASSOC { get; set; }
        public string x103K_CRED_BUREAU_RPT_IND { get; set; }
        public string x103K_CREDIT_SCORE_TYPE { get; set; }
        public string x103K_CREDIT_SCORE_REF_NUM { get; set; }
        public string x103K_CRED_BUREAU_STATUS_CODE { get; set; }
        public string x103K_CRED_CONS_INFO_IND { get; set; }
        public string x103K_CRED_COMP_COND_CD { get; set; }
        public string x103K_CRED_BUREAU_COMM_IND { get; set; }
        public string x103K_ALT_REC_CD_1 { get; set; }
        public string x103K_ALT_ASSOC_CD_1 { get; set; }
        public string x103K_DATE_LAST_PR_IN_PYMNT { get; set; }
        public string x103K_ALT_REC_CD_2 { get; set; }
        public string x103K_ALT_ASSOC_CD_2 { get; set; }
        public decimal x103K_CR_BUR_PAST_DUE { get; set; }
        public string x103K_ALT_REC_CD_3 { get; set; }
        public string x103K_ALT_ASSOC_CD_3 { get; set; }
        public string x103L_CREDIT_SC { get; set; }
        public string x103L_CREDIT_SC_DT { get; set; }
        public string x103L_CREDIT_SC_TYPE { get; set; }
        public string x103L_DEBT_INCOME_RATIO { get; set; }
        public string x103L_CURRENT_LTV { get; set; }
        public string x103L_APPL_DATE { get; set; }
        public decimal x103L_DEBT_AMOUNT { get; set; }
        public string x103L_CONTRACT_ADDS { get; set; }
        public decimal x103L_LC_CAP_AMOUNT { get; set; }
        public string x103L_PRODUCT { get; set; }
        public string x103L_CAMPAIGN { get; set; }
        public string x103L_PROGRAM { get; set; }
        public string x103L_APPL_SOURCE { get; set; }
        public string x103L_WORKPACKAGE_NO { get; set; }
        public string x103L_APPL_OVERRIDE_IND { get; set; }
        public string x103L_WORKPACKAGE_TYPE { get; set; }
        public string x103L_FINAL_APPROVAL_OFFICER { get; set; }
        public string x103L_CREDIT_RVW_OFFICER { get; set; }
        public string x103L_CREDIT_LST_REV_DT { get; set; }
        public string x103L_EXCEPT_APPROVAL_OFFICER { get; set; }
        public string x103L_OCCUPANCY { get; set; }
        public string x103M_APPRAISAL_TYPE { get; set; }
        public string x103M_APPRAISER { get; set; }
        public string x103M_APPRAISAL_DATE { get; set; }
        public decimal x103M_APPRAISAL_AMT { get; set; }
        public decimal x103M_ORIG_RE_LTV { get; set; }
        public decimal x103M_ORIG_RE_APPL_AMT { get; set; }
        public decimal x103M_CURR_RE_LTV { get; set; }
        public decimal x103M_CURR_RE_APPL_AMT { get; set; }
        public string x103M_NUM_PROP { get; set; }
        public int x103M_TOT_OFF_SF { get; set; }
        public decimal x103M_NUM_UNITS { get; set; }
        public int x103M_TOT_RES_SF { get; set; }
        public int x103M_NUM_RES_ROOM { get; set; }
        public int x103M_TOT_RETAIL_SF { get; set; }
        public int x103M_TOT_COMM_SF { get; set; }
        public string x103M_TOT_ACREAGE { get; set; }
        public decimal x103M_TOT_RENT_SF { get; set; }
        public decimal x103M_TOT_BLDG_SF { get; set; }
        public decimal x103M_FIRST_LIEN_AMT { get; set; }
        public string x103M_LIEN_POSITION { get; set; }
        public string x103M_LIEN_HOLDER_NAME { get; set; }
        public string x103M_OLD_LOAN_NUMBER { get; set; }
        public string x103M_SYSTEM_CONV_FROM { get; set; }
        public string x103N_AFS_COMM_OBLIGOR { get; set; }
        public string x103N_AFS_COMM_OBLIGATION { get; set; }
        public string x103N_U_NUMERIC3 { get; set; }
        public string x103N_ORIGINATING_RU { get; set; }
        public string x103N_USER_STI_NUMERIC_A { get; set; }
        public string x103N_LAST_REPRICE_INDEX { get; set; }
        public string x103N_USER_STI_NUMERIC_B { get; set; }
        public string x103N_CALL_DATE { get; set; }
        public string x103N_USER_ALPHA_5 { get; set; }
        public string x103N_COMMIT_DATE { get; set; }
        public string x103O_CONTIGUOUS_PROPERTY_IND { get; set; }
        public string x103O_ORIG_AMORTIZATION_DATE { get; set; }
        public string x103O_LOAN_REN_CODE { get; set; }
        public string x103O_MODIFICATION_DATE { get; set; }
        public string x103O_RENEWAL_DATE { get; set; }
        public string x103O_INDEX_NAME { get; set; }
        public string x103O_ADV_NOTICE_PERIOD { get; set; }
        public decimal x103O_INDEX_RATE { get; set; }
        public string x103O_REN_PAYMENT_TY { get; set; }
        public string x103O_INDEX_DATE { get; set; }
        public string x103O_SECONDARY_FIN_IND { get; set; }
        public decimal x103O_MARGIN1 { get; set; }
        public string x103O_AMORTIZATION_TERM { get; set; }
        public decimal x103O_FEE_PERCENT { get; set; }
        public string x103O_BALLOON_DATE { get; set; }
        public decimal x103O_FEE_AMOUNT { get; set; }
        public string x103O_CALL_DATE { get; set; }
        public string x103O_FEE_BAL_TYPE { get; set; }
        public string x103O_COMMENTS { get; set; }
        public string x103O_REFI_BANK1 { get; set; }
        public string x103O_REFI_OBLIGOR1 { get; set; }
        public string x103O_REFI_OBLIGATION1 { get; set; }
        public decimal x103O_REFI_AMOUNT1 { get; set; }
        public string x103O_REFI_BANK2 { get; set; }
        public string x103O_REFI_OBLIGOR2 { get; set; }
        public string x103O_REFI_OBLIGATION2 { get; set; }
        public decimal x103O_REFI_AMOUNT2 { get; set; }
        public string x103O_REFI_BANK3 { get; set; }
        public string x103O_REFI_OBLIGOR3 { get; set; }
        public string x103O_REFI_OBLIGATION3 { get; set; }
        public decimal x103O_REFI_AMOUNT3 { get; set; }
        public string x103O_REFI_BANK4 { get; set; }
        public string x103O_REFI_OBLIGOR4 { get; set; }
        public string x103O_REFI_OBLIGATION4 { get; set; }
        public decimal x103O_REFI_AMOUNT4 { get; set; }
        public string x103O_REFI_BANK5 { get; set; }
        public string x103O_REFI_OBLIGOR5 { get; set; }
        public string x103O_REFI_OBLIGATION5 { get; set; }
        public decimal x103O_REFI_AMOUNT5 { get; set; }
        public decimal x103P_TOTAL_EXPENSE { get; set; }
        public string x103P_LAST_FISCAL_YEAR { get; set; }
        public decimal x103P_NET_OPERATION_INCOME { get; set; }
        public string x103P_FISCAL_YEAR_MONTH { get; set; }
        public decimal x103P_TOTAL_DEBT_SERVICE { get; set; }
        public string x103P_DEBT_SERVICE_CHARGE { get; set; }
        public decimal x103P_GROSS_INCOME { get; set; }
        public string x103P_EXPENSE_RATIO { get; set; }
        public decimal x103P_ROOM_EGI { get; set; }
        public string x103P_RENT_ROLL_DATE { get; set; }
        public decimal x103P_SF_EGI { get; set; }
        public decimal x103P_NOTE_RATE { get; set; }
        public string x103P_LOAN_GRADE { get; set; }
        public string x103P_CD_CC_IND { get; set; }
        public string x103P_SWAP_IND { get; set; }
        public decimal x103P_NON_RE_COLLATERAL_PERC { get; set; }
        public decimal x103P_RE_COLLATERAL_PERCENT { get; set; }
        public decimal x103P_RE_LTV { get; set; }
        public string x103P_LAST_INSPECT_DATE { get; set; }
        public decimal x103P_44XX_TOL_OVER_AMT { get; set; }
        public decimal x103P_44XX_TOL_SHORT_AMT { get; set; }
        public short x103P_44XX_TOL_OVER_PCT { get; set; }
        public decimal x103P_44XX_TOL_SHORT_PCT { get; set; }
        public string x103P_PMT_PRE_JAN { get; set; }
        public string x103P_PMT_PRE_FEB { get; set; }
        public string x103P_PMT_PRE_MAR { get; set; }
        public string x103P_PMT_PRE_APR { get; set; }
        public string x103P_PMT_PRE_MAY { get; set; }
        public string x103P_PMT_PRE_JUN { get; set; }
        public string x103P_PMT_PRE_JUL { get; set; }
        public string x103P_PMT_PRE_AUG { get; set; }
        public string x103P_PMT_PRE_SEP { get; set; }
        public string x103P_PMT_PRE_OCT { get; set; }
        public string x103P_PMT_PRE_NOV { get; set; }
        public string x103P_PMT_PRE_DEC { get; set; }
        public string x103P_PMT_CUR_JAN { get; set; }
        public string x103P_PMT_CUR_FEB { get; set; }
        public string x103P_PMT_CUR_MAR { get; set; }
        public string x103P_PMT_CUR_APR { get; set; }
        public string x103P_PMT_CUR_MAY { get; set; }
        public string x103P_PMT_CUR_JUN { get; set; }
        public string x103P_PMT_CUR_JUL { get; set; }
        public string x103P_PMT_CUR_AUG { get; set; }
        public string x103P_PMT_CUR_SEP { get; set; }
        public string x103P_PMT_CUR_OCT { get; set; }
        public string x103P_PMT_CUR_NOV { get; set; }
        public string x103P_PMT_CUR_DEC { get; set; }
        public string x103I_DATA_PRESENT_SW { get; set; }
        public string x103I_INDIC_DATA_YEAR { get; set; }
        public string x103I_INDIC_DATA_TYPE { get; set; }
        public string x103I_INDIC_DATA_MAKE { get; set; }
        public string x103I_INDIC_DATA_MODEL { get; set; }
        public string x103I_INDIC_DATA_SERIAL { get; set; }
        public string x103I_INDIC_DATA_ADDRESS_1 { get; set; }
        public string x103I_INDIC_DATA_ADDRESS_2 { get; set; }
        public string x103I_INDIC_DATA_CITY { get; set; }
        public string x103I_INDIC_DATA_STATE { get; set; }
        public string x103I_INDIC_DATA_ZIP_CODE { get; set; }
        public decimal x103I_INDIC_DATA_USER_AMOUNT { get; set; }
        public string x103I_INDIC_DATA_USER_CODE { get; set; }
        public string x103I_INDIC_DATA_DATE_RECVD { get; set; }
        public string x103I_INDIC_DATA_DATE_REL { get; set; }
        public string x103I_INDIC_DATA_LOC_RECVD { get; set; }
        public string x103I_INDIC_DATA_LOC_HELD { get; set; }
        public string x103I_DISPOSITION_ONE { get; set; }
        public string x103I_INDIC_DATA_ID_NUMBER { get; set; }
        public string x103I_DISPOSITION_TWO { get; set; }
        public string x103I_INDIC_DATA_FILING_REF { get; set; }
        public string x103I_DISPOSITION_THREE { get; set; }
        public string x103I_INDIC_DATA_DESC_1 { get; set; }
        public string x103I_INDIC_DATA_DESC_2 { get; set; }
        public string x103I_PDI_REQ_CODE { get; set; }
        public string x103I_PDI_STATUS_CODE { get; set; }
        public string x103I_PDI_POLICY_NUMB { get; set; }
        public string x103I_PDI_STATUS_DATE { get; set; }
        public string x103I_PDI_COMPANY { get; set; }
        public string x103I_PDI_EXP_DATE { get; set; }
        public string x103I_PDI_AGENT_NAME { get; set; }
        public string x103J_DATA_PRESENT_SW { get; set; }
        public string x103J_FORE_ABAND_POST_DATE { get; set; }
        public string x103J_FORE_ABAND_DATE { get; set; }
        public string x103J_LIABILITY_IND { get; set; }
        public decimal x103J_OUTSTANDING_BAL { get; set; }
        public decimal x103J_FORE_BID_PRICE { get; set; }
        public decimal x103J_APPRAISAL_VALUE { get; set; }
        public string x103J_DESC_1 { get; set; }
        public string x103J_DESC_2 { get; set; }
        public decimal x103J_ODD_DAYS_INT_AMT { get; set; }
        public string x103J_DAYS_TO_CHG_PAYOFF { get; set; }
        public string x103J_ODD_DAYS_EARN_IND { get; set; }
        public string x103J_DAYS_TO_CHG_INS { get; set; }
        public decimal x103J_PART_PAYMENT { get; set; }
        public string x103J_NUMB_PAYMENTS_MADE { get; set; }
        public decimal x103J_AMT_FINANCED { get; set; }
        public string x103J_COLL_RECD_IND { get; set; }
        public string x103J_PREPAID_FIN_CHGS { get; set; }
        public string x103J_VARY_RATE_IND { get; set; }
        public decimal x103J_APR { get; set; }
        public string x103J_APR_VERIF_IND { get; set; }
        public string x103J_78TH_EARN_DAY { get; set; }
        public string x103J_78TH_EARN_DAY_INS { get; set; }
        public string x103J_12_MONTH_PYMNT_HIST { get; set; }


    }
}
